spring.application.name=neoAPP

# Conectandonos a una BD

#1. Info general de la conexion
spring.datasource.url=jdbc:H2:mem:neoapp_db
spring.datasource.username=sa
spring.datasource.password=

#2. Habilitar la BD en memoria (H2)+
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#3. Habilitar el JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create